version: '3.1'

services:

  php:
    restart: always
    build:
      context: '.'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  php:
  db:
  adminer:
